---
extends: default

rules:
  line-length:
    max: 80
    level: error
    ignore: |
      .github/workflows/
  truthy:
    allowed-values: ['true', 'false', 'on']
  comments:
    min-spaces-from-content: 1
    ignore: |
      .github/workflows/
