name: 'Terragrunt GitHub Actions'
on:
  pull_request:
    branches:
      - main

env:
  TOFU_VERSION: '1.8.1'
  TG_VERSION: '0.67.0'
  WORKING_DIR: 'aws'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  tg-plan:
    uses: yashrajdighe/github-actions-reusable-workflows/.github/workflows/tg-plan.yaml@add-tg-plan-workflow
    with:
      enable_oidc_debugger: true
      role_to_assume: ${{ vars.TERRAFORM_RO_IAM_ROLE }}
      working_directory: 'aws'
      tofu_version: '1.8.1'
      tg_version: '0.67.0'
      github_token: ${{ secrets.GITHUB_TOKEN }}
