name: 'Terragrunt GitHub Actions'
on:
  pull_request:
    branches:
      - main

env:
  tofu_version: '1.8.1'
  tg_version: '0.67.0'
  working_dir: 'aws'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  tg-plan:
    runs-on: ubuntu-latest
    uses: yashrajdighe/github-actions-reusable-workflows/.github/workflows/tg-plan.yaml@add-tg-plan-workflow
    with:
      enable-oidc-debugger: true
      role-to-assume: var.TERRAFORM_RO_IAM_ROLE
      working-directory: 'aws'
      tofu-version: '1.8.1'
      tg-version: '0.67.0'
